Update patch set 2
Patch Set 2: Code-Review-1

The example query gives me:

```
  echo -n -e ' This ist a start of a text. And this is a sentence!!! But what the hack????\x03\x03\x0aAnd this is another text.\n\x03\nAnd this a sentence without marker\n' | java -jar target/KorAP-Tokenizer-1.3-SNAPSHOT.jar --positions --sentence-boundaries
```

```
  Exception in thread "main" java.lang.NoClassDefFoundError: picocli/CommandLine$Help$ColorScheme$Builder
	at de.ids_mannheim.korap.tokenizer.Main.<clinit>(Main.java:99)
Caused by: java.lang.ClassNotFoundException: picocli.CommandLine$Help$ColorScheme$Builder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more
```

Patch-set: 2
Reviewer: Gerrit User 19 <19@626241b7-b7d0-4197-b843-1ee23887649c>
Label: Code-Review=-1
Attention: {"person_ident":"Gerrit User 6 \u003c6@626241b7-b7d0-4197-b843-1ee23887649c\u003e","operation":"ADD","reason":"reviewer or cc replied"}
Attention: {"person_ident":"Gerrit User 19 \u003c19@626241b7-b7d0-4197-b843-1ee23887649c\u003e","operation":"REMOVE","reason":"removed on reply"}